export {default as Home} from './Home'
export {default as OutletPage} from './OutletPage'
export {default as Product} from './Product'
export {default as SingleProduct} from './SingleProduct'
export {default as Cart} from './Cart'